# Generated by Django 4.0.3 on 2022-03-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=15)),
                ('num', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['-document', '-num'],
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(default='Original', max_length=15)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-type'],
            },
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='api.documents')),
                ('translated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated', to='api.documents')),
            ],
            options={
                'db_table': 'translations',
                'ordering': ['-original'],
            },
        ),
        migrations.CreateModel(
            name='Passages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.CharField(max_length=50)),
                ('num', models.PositiveSmallIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapters')),
            ],
            options={
                'db_table': 'passages',
                'ordering': ['-chapter', '-num'],
            },
        ),
        migrations.AddField(
            model_name='chapters',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documents'),
        ),
    ]
