# Generated by Django 4.0.3 on 2022-03-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id_Chapter', models.IntegerField(primary_key=True, serialize=False)),
                ('chapter', models.CharField(max_length=15)),
                ('num', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['-id_Document', '-num'],
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id_Document', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('0', 'Original'), ('1', 'Translation')], default='Original', max_length=15)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-type'],
            },
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id_Translation', models.IntegerField(primary_key=True, serialize=False)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='api.documents')),
                ('translated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated', to='api.documents')),
            ],
            options={
                'db_table': 'translations',
                'ordering': ['-original'],
            },
        ),
        migrations.CreateModel(
            name='Passages',
            fields=[
                ('id_Passage', models.IntegerField(primary_key=True, serialize=False)),
                ('passage', models.CharField(max_length=50)),
                ('num', models.PositiveSmallIntegerField()),
                ('id_Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapters')),
            ],
            options={
                'db_table': 'passages',
                'ordering': ['-id_Chapter', '-num'],
            },
        ),
        migrations.AddField(
            model_name='chapters',
            name='id_Document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documents'),
        ),
    ]
