# Generated by Django 4.0.3 on 2022-03-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='num',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='passages',
            name='num',
            field=models.CharField(max_length=2),
        ),
    ]
