# Generated by Django 4.0.3 on 2022-03-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chapters_num_alter_passages_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'ordering': ['document', 'num']},
        ),
        migrations.AlterModelOptions(
            name='passages',
            options={'ordering': ['chapter', 'num']},
        ),
        migrations.AlterModelOptions(
            name='translations',
            options={'ordering': ['original']},
        ),
        migrations.AlterField(
            model_name='passages',
            name='passage',
            field=models.CharField(max_length=500),
        ),
    ]
